name: Glitch Project Sync

on: [push]

jobs:
  # Minimal test of the GitHub Action
  # (only runs on pushes to the `main` branch)
  # Glitch Project: https://glitch.com/edit/#!/github-action
  sync:
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.AUTHTOKEN }}'
          project-id: '${{ secrets.PROJECTID }}'